# introduction to Python 

## Data Types

In [1]:
a = 10
b = 20

In [2]:
type(a)

int

In [3]:
type('25')

str

In [4]:
type(45)

int

In [5]:
type(3.1445)

float

## import the library

In [6]:
import math as mth

In [7]:
x = 4.5
y = 5

p  = 250
q = 310

print(mth.ceil(x))
print(mth.floor(x))
print(mth.factorial(5))
print(mth.gcd(a,b))

5
4
120
10


# String Operations in Python
    1. Capitalize
    2. Uppercase
    3. Lowercase
    4. Replace
    

In [9]:
My_class = "this is DATA SCIENCE class : welcome all"

print("Before capitalizing:", My_class)
print("After Capitalizing:", My_class.capitalize())


Before capitalizing: this is DATA SCIENCE class : welcome all
After Capitalizing: This is data science class : welcome all


In [10]:
print("After converting into Uppercase:",My_class.upper())

After converting into Uppercase: THIS IS DATA SCIENCE CLASS : WELCOME ALL


In [11]:
My_Upper_Class = My_class.upper()

In [12]:
My_Upper_Class

'THIS IS DATA SCIENCE CLASS : WELCOME ALL'

In [13]:
My_lower_Class = My_Upper_Class.lower()

In [15]:
print(My_lower_Class)

this is data science class : welcome all


In [16]:
My_Upper_Class.replace('SCIENCE','Artificail Intelligence')

'THIS IS DATA Artificail Intelligence CLASS : WELCOME ALL'

In [17]:
My_Upper_Class.replace('data','AI')

'THIS IS DATA SCIENCE CLASS : WELCOME ALL'

In [18]:
My_Upper_Class = My_Upper_Class.replace('SCIENCE','Artificail Intelligence')

In [19]:
My_Upper_Class

'THIS IS DATA Artificail Intelligence CLASS : WELCOME ALL'

In [20]:
print(My_Upper_Class + My_lower_Class)

THIS IS DATA Artificail Intelligence CLASS : WELCOME ALLthis is data science class : welcome all


# Numpy & random library

In [21]:
# import library
import numpy as np
import random

In [23]:
num = np.random.rand(1) # 1-Dimensional

print(num)
print(num.shape)
print(num.ndim)
print(" ")

[0.52480512]
(1,)
1
 


In [24]:
num_2 = np.random.rand(4)

print(num_2)
print(num_2.shape)
print(num_2.ndim)

[0.52903689 0.27135472 0.70032981 0.32962737]
(4,)
1


### 2 -Dimensional Numpy arrays

In [26]:
# decleration of 2d- numpy array
arr_2d = np.random.rand(3,4) 

print(arr_2d)
print(arr_2d.shape)
print(arr_2d.ndim)
print(arr_2d.size)

[[0.95554917 0.86654613 0.97689926 0.44798845]
 [0.73525477 0.94047623 0.36605561 0.24899611]
 [0.398848   0.38254062 0.43675949 0.89650846]]
(3, 4)
2
12


In [27]:
arr_2d_ex2 = np.array([[1, 3, 5, 4],
                       [2, 4, 6, 8]])

print(arr_2d_ex2.shape)
print(arr_2d_ex2)
print(arr_2d_ex2.ndim)
print(arr_2d_ex2.size)

(2, 4)
[[1 3 5 4]
 [2 4 6 8]]
2
8


In [29]:
arr_3d =np.array([[[1]], 
                  [[2]]])
print(arr_3d.shape)
print(arr_3d.ndim)

(2, 1, 1)
3
